spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DimLighter/config-repo
          username: DimLighter
          password: q3318850
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/